//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.27 at 11:57:01 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/person", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.example.person;
